development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c3c5cd14f6fd385675364bffe2052dde@dory.redistogo.com:9587/
  channel_prefix: chatroom_channel
